service: swift-sprinter-rest-api
frameworkVersion: '3'
configValidationMode: warn

package:
    artifact: build/Products/Products.zip

custom:
    tableName: 'products-table-${sls:stage}'
    keyName: 'sku'

provider:
    name: aws
    region: eu-west-1
    httpApi:
        payload: '2.0'
        cors: true
    # Change to provided.al2 if you build with M1
    runtime: provided
    # Change to arm64 if you build with M1
    architecture: x86_64
    environment:
        DYNAMO_DB_TABLE_NAME: '${self:custom.tableName}'
        DYNAMO_DB_KEY: '${self:custom.keyName}'
    iam:
        role:
            statements:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource: "*"
                - Effect: Allow
                  Action:
                    - dynamodb:UpdateItem
                    - dynamodb:PutItem
                    - dynamodb:GetItem
                    - dynamodb:DeleteItem
                    - dynamodb:Query
                    - dynamodb:Scan
                    - dynamodb:DescribeTable
                  Resource:
                    - { Fn::GetAtt: [ProductsTable, Arn] }

functions:
    createProduct:
        handler: create
        memorySize: 256
        description: "[${sls:stage}] Create Product"
        events:
            - httpApi:
                path: /products
                method: post
    readProduct:
        handler: read
        memorySize: 256
        description: "[${sls:stage}] Get Product"
        events:
            - httpApi:
                path: /products/{sku}
                method: get
    updateProduct:
        handler: update
        memorySize: 256
        description: "[${sls:stage}] Update Product"
        events:
            - httpApi:
                path: /products
                method: put
    deleteProduct:
        handler: delete
        memorySize: 256
        description: "[${sls:stage}] Delete Product"
        events:
            - httpApi:
                path: /products/{sku}
                method: delete
    listProducts:
        handler: list
        memorySize: 256
        description: "[${sls:stage}] List Products"
        events:
            - httpApi:
                path: /products
                method: get

resources:
    Resources:
        ProductsTable:
            Type: AWS::DynamoDB::Table
            Properties:
                TableName: ${self:custom.tableName}
                AttributeDefinitions:
                    - AttributeName: ${self:custom.keyName}
                      AttributeType: S
                KeySchema:
                    - AttributeName: ${self:custom.keyName}
                      KeyType: HASH
                BillingMode: PAY_PER_REQUEST