service: swift-sprinter-rest-api
variablesResolutionMode: 20210326
frameworkVersion: '3'
configValidationMode: warn

package:
    individually: true

custom:
    tableName: 'products-table-${sls:stage}'

provider:
    name: aws
    httpApi:
        payload: '2.0'
        cors: true
    # Change to provided.al2 if you build with M1
    runtime: provided
    lambdaHashingVersion: "20201221"
    # Change to arm64 if you build with M1
    architecture: x86_64
    environment:
        PRODUCTS_TABLE_NAME: '${self:custom.tableName}'
    iam:
        role:
            statements:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource: "*"
                - Effect: Allow
                  Action:
                    - dynamodb:UpdateItem
                    - dynamodb:PutItem
                    - dynamodb:GetItem
                    - dynamodb:DeleteItem
                    - dynamodb:Query
                    - dynamodb:Scan
                    - dynamodb:DescribeTable
                  Resource:
                    - { Fn::GetAtt: [ProductsTable, Arn] }

layers:
    swift-lambda-runtime:
        path: ./build/swift-lambda-runtime
        name: aws-swift-sprinter-lambda-runtime
        description: AWS Lambda Custom Runtime for Swift-Sprinter   

functions:
    createProduct:
        handler: build/Products.create
        package:
            individually: true
            patterns:
                - "!**/*"
                - "build/Products"
        memorySize: 256
        layers:
           - { Ref: "SwiftDashlambdaDashruntimeLambdaLayer" }
        description: "[${sls:stage}] Create Product"
        events:
            - httpApi:
                path: /products
                method: post
    readProduct:
        handler: build/Products.read
        package:
            individually: true
            patterns:
                - "!**/*"
                - "build/Products"
        memorySize: 256
        layers:
            - { Ref: SwiftDashlambdaDashruntimeLambdaLayer }
        description: "[${sls:stage}] Get Product"
        events:
            - httpApi:
                path: /products/{sku}
                method: get
    updateProduct:
        handler: build/Products.update
        package:
            individually: true
            patterns:
                - "!**/*"
                - "build/Products"
        memorySize: 256
        layers:
            - { Ref: SwiftDashlambdaDashruntimeLambdaLayer }
        description: "[${sls:stage}] Update Product"
        events:
            - httpApi:
                path: /products
                method: put
    deleteProduct:
        handler: build/Products.delete
        package:
            individually: true
            patterns:
                - "!**/*"
                - build/Products
        memorySize: 256
        layers:
            - { Ref: SwiftDashlambdaDashruntimeLambdaLayer }
        description: "[${sls:stage}] Delete Product"
        events:
            - httpApi:
                path: /products/{sku}
                method: delete
    listProducts:
        handler: build/Products.list
        package:
            individually: true
            patterns:
                - "!**/*"
                - "build/Products"
        memorySize: 256
        layers:
            - { Ref: SwiftDashlambdaDashruntimeLambdaLayer }
        description: "[${sls:stage}] List Products"
        events:
            - httpApi:
                path: /products
                method: get

resources:
    Resources:
        ProductsTable:
            Type: AWS::DynamoDB::Table
            Properties:
                TableName: ${self:custom.tableName}
                AttributeDefinitions:
                    - AttributeName: sku
                      AttributeType: S
                KeySchema:
                    - AttributeName: sku
                      KeyType: HASH
                BillingMode: PAY_PER_REQUEST